version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: weekly
      day: "sunday"
    commit-message:
      prefix: "deps(go):"
    labels:
      - "dependencies"
